### ISSUE TITLE
video-extensions.json returns empty object

### ISSUE THREAD

**Issue by ericandrewlewis** [sindresorhus/video-extensions#2]
In trying to use [is-video](https://www.npmjs.com/package/is-video) in the browser I saw that `require('video-extensions')` was returning an empty object.

I changed the first line of `video-extensions.json` from

``` js
[
// ...
]
```

to

``` js
exports = module.exports = [
// ...
]
```

I'm sure this has something to do with the differences in Node.js' native commonJS implementation vs. how webpack performs it but I'm not sure exactly what.

This also affects the `image-extensions` module.

**Comment by sindresorhus** [comment]
Open an issue on Webpack. This works fine on Node.js and with Browserify.
